name: Selenium Test Automation

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"  # Match your project’s Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install from requirements file

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1  # Installs latest Chrome
          
      - name: Run Selenium Tests
        run: |
          pytest --html=report/test_report.html --self-contained-html

      - name: Upload Test Report
        if: always()  # Ensures upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report/test_report.html
